name: aile_cuzdani
description: Aile içi gelir/gider takibi yapmak artık çok kolay!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+20

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  intl: ^0.18.0
  dropdown_search: ^5.0.3
  loading_animations: ^2.2.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.0.7
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  device_info_plus: ^8.0.0
  flutter_local_notifications: ^12.0.4
  package_info_plus: ^4.0.2
  showcaseview: ^2.0.0+1
  rate_my_app: ^1.1.3
  html: ^0.15.4
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/
    - assets/icons/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/font/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/font/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/font/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/font/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/JosefinSans-Bold.ttf
          weight: 700
